Repository nonsoolmate-official/nonsoolmate-server, pull requests merged in 2024-09, with the labels that each got.

#113 [FIX] cd 스크립트 변경
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: 🔨 fix, 🍀song

#114 [FIX] ci,cd 스크립트 변경
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: 🔨 fix, 🍀song

#124 [FEAT] billing 엔티티 billingId 컬럼 추가 및 pk 변경
  nonsoolmate-db-core/src/main/java/com/nonsoolmate/payment/entity/Billing.java
Labels: 🎁 feature, 💜euna

#136 [FIX] 선택 대학 조회 로직 수정
  nonsoolmate-api/src/main/java/com/nonsoolmate/selectCollege/service/SelectCollegeService.java
  nonsoolmate-db-core/src/main/java/com/nonsoolmate/selectCollege/repository/SelectCollegeRepository.java
Labels: 🔨 fix, 🍀song

#142 [TEST] 카드 등록 API 서비스 계층 테스트코드 작성
  nonsoolmate-api/src/test/java/com/nonsoolmate/payment/service/BillingServiceTest.java
Labels: 🎫 test, 💜euna
