Repository nonsoolmate-official/nonsoolmate-server, pull requests merged in 2024-07, with the labels that each got.

#4 [FEAT] 로깅 AOP 구현
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/aop/ExecutionLoggingAop.java
Labels: 🎁 feature, 🍀song

#15 [FIX] cd 스크립트 수정
  .github/workflows/dev-CD.yml
Labels: bug

#17 [FIX] cd 스크립트 수정
  .github/workflows/dev-CD.yml
Labels: bug, 🍀song

#21 [FIX] dev-CD scp 명령어 실행 job 변경
  .github/workflows/dev-CD.yml
Labels: 🔨 fix, 💜euna

#26 [FIX] known_hosts 추가
  .github/workflows/dev-CD.yml
Labels: 🔨 fix, 💜euna

#28 [FIX] scp 접속 시 hostname이 아닌 dev_server_ip로 접속하도록 수정
  .github/workflows/dev-CD.yml
Labels: 🔨 fix, 💜euna

#30 [SETTING] application-prod.yml aws 관련 변수 분리
  nonsoolmateServer/src/main/resources/application-prod.yml
Labels: 🪄 setting, 💜euna

#36 [CHORE] 레디스 url 변경
  nonsoolmateServer/src/main/resources/application-prod.yml
Labels: ✨ patch

#37 [DEPLOY] v1.0.0
  .github/release-drafter-config.yml
  .github/workflows/prod-CD.yml
  nonsoolmateServer/Dockerfile
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/redis/config/RedisConfig.java
Labels: ✨ major, 💜euna

#45 [DEPLOY] v1.0.1
  .github/release-drafter-config.yml
  nonsoolmateServer/src/main/resources/application-dev.yml
  nonsoolmateServer/src/main/resources/application-local.yml
  nonsoolmateServer/src/main/resources/application-prod.yml
  nonsoolmateServer/src/main/resources/application-test.yml
Labels: 🚀 deploy, ✨ patch

#48 [INFRA] localhost -> redis로 수정
  nonsoolmateServer/src/main/resources/application-dev.yml
Labels: 🍀song, ⚒️ infra

#50 [FIX] osiv 끄기 및 yml 정리
  nonsoolmateServer/src/main/resources/application-dev.yml
  nonsoolmateServer/src/main/resources/application-local.yml
  nonsoolmateServer/src/main/resources/application-prod.yml
Labels: 🔨 fix

#55 [CHORE] local yml 수정
  nonsoolmateServer/src/main/resources/application-local.yml
Labels: 📝 chore

#61 [FIX] 초기화 메서드 수정
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerInitController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerInitService.java
Labels: 🔨 fix

#65 [DEPLOY] v1.0.2
  .github/workflows/dev-CD.yml
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/exception/AuthExceptionType.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/auth/service/AuthService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/controller/ExamRecordController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/ExamRecord.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/entity/enums/CorrectionFileName.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/repository/ExamRecordRepository.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/examRecord/service/ExamRecordService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/entity/Member.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/member/repository/MemberRepository.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/ExamApi.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/controller/ExamController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/entity/ExamImage.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/ExamImageRepository.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/repository/ExamRepository.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/domain/university/service/ExamService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/aws/FolderName.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/oauth/service/NaverAuthService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/external/oauth/service/vo/NaverMemberVO.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerInitController.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/controller/ServerInitService.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/security/config/SecurityConfig.java
  nonsoolmateServer/src/main/java/com/nonsoolmate/nonsoolmateServer/global/swagger/config/SwaggerConfig.java
  nonsoolmateServer/src/main/resources/application-dev.yml
  nonsoolmateServer/src/main/resources/application-local.yml
  nonsoolmateServer/src/main/resources/application-prod.yml
  nonsoolmateServer/src/main/resources/application-test.yml
Labels: 🚀 deploy, ✨ patch
